package com.sodashop.entity;
// Generated Apr 27, 2020, 1:10:24 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderDetailId generated by hbm2java
 */
@Embeddable

public class OrderDetailId implements java.io.Serializable {

	private Integer orderId;
	private Date dateOrdered;
	private Integer quantity;
	private Float subtotal;
	private Integer sodaId;

	public OrderDetailId() {
	}

	public OrderDetailId(Date dateOrdered) {
		this.dateOrdered = dateOrdered;
	}

	public OrderDetailId(Integer orderId, Date dateOrdered, Integer quantity, Float subtotal, Integer sodaId) {
		this.orderId = orderId;
		this.dateOrdered = dateOrdered;
		this.quantity = quantity;
		this.subtotal = subtotal;
		this.sodaId = sodaId;
	}

	@Column(name = "order_id")
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@Column(name = "date_ordered", nullable = false, length = 10)
	public Date getDateOrdered() {
		return this.dateOrdered;
	}

	public void setDateOrdered(Date dateOrdered) {
		this.dateOrdered = dateOrdered;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "subtotal", precision = 12, scale = 0)
	public Float getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(Float subtotal) {
		this.subtotal = subtotal;
	}

	@Column(name = "soda_id")
	public Integer getSodaId() {
		return this.sodaId;
	}

	public void setSodaId(Integer sodaId) {
		this.sodaId = sodaId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderDetailId))
			return false;
		OrderDetailId castOther = (OrderDetailId) other;

		return ((this.getOrderId() == castOther.getOrderId()) || (this.getOrderId() != null
				&& castOther.getOrderId() != null && this.getOrderId().equals(castOther.getOrderId())))
				&& ((this.getDateOrdered() == castOther.getDateOrdered())
						|| (this.getDateOrdered() != null && castOther.getDateOrdered() != null
								&& this.getDateOrdered().equals(castOther.getDateOrdered())))
				&& ((this.getQuantity() == castOther.getQuantity()) || (this.getQuantity() != null
						&& castOther.getQuantity() != null && this.getQuantity().equals(castOther.getQuantity())))
				&& ((this.getSubtotal() == castOther.getSubtotal()) || (this.getSubtotal() != null
						&& castOther.getSubtotal() != null && this.getSubtotal().equals(castOther.getSubtotal())))
				&& ((this.getSodaId() == castOther.getSodaId()) || (this.getSodaId() != null
						&& castOther.getSodaId() != null && this.getSodaId().equals(castOther.getSodaId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOrderId() == null ? 0 : this.getOrderId().hashCode());
		result = 37 * result + (getDateOrdered() == null ? 0 : this.getDateOrdered().hashCode());
		result = 37 * result + (getQuantity() == null ? 0 : this.getQuantity().hashCode());
		result = 37 * result + (getSubtotal() == null ? 0 : this.getSubtotal().hashCode());
		result = 37 * result + (getSodaId() == null ? 0 : this.getSodaId().hashCode());
		return result;
	}

}
