package com.sodashop.entity;
// Generated May 7, 2020, 4:49:55 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * OrderDetailId generated by hbm2java
 */
@Embeddable
public class OrderDetailId implements java.io.Serializable {
	private Soda soda;
	private SodaOrder sodaOrder;

	public OrderDetailId() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "soda_id", insertable = false, updatable = false, nullable = false)
	public Soda getSoda() {
		return this.soda;
	}

	public void setSoda(Soda soda) {
		this.soda = soda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", insertable = false, updatable = false, nullable = false)
	public SodaOrder getSodaOrder() {
		return this.sodaOrder;
	}

	public void setSodaOrder(SodaOrder sodaOrder) {
		this.sodaOrder = sodaOrder;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((soda == null) ? 0 : soda.hashCode());
		result = prime * result + ((sodaOrder == null) ? 0 : sodaOrder.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		OrderDetailId other = (OrderDetailId) obj;
		if (soda == null) {
			if (other.soda != null)
				return false;
		} else if (!soda.equals(other.soda))
			return false;
		if (sodaOrder == null) {
			if (other.sodaOrder != null)
				return false;
		} else if (!sodaOrder.equals(other.sodaOrder))
			return false;
		return true;
	}
	

}
